#!/usr/bin/env bash
# Extensive DinD compatibility battery: runs every harness tool AND every
# real-gateway E2E, serially (they share fixed container names / ports), and
# writes one combined report to docs/dind/RESULTS.md.
#
#   bash battery.sh                # everything
#   bash battery.sh kafka registry # a subset (harness tool names or e2e-* names)
#   BATTERY_SKIP_E2E=1 bash battery.sh   # harness tools only (no gateway build)
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$HERE/../../.." && pwd)"
source "$HERE/lib.sh"

# Harness tools (fast, self-contained; run on a bridge network).
HARNESS=(compose testcontainers buildx privileged k3d localstack act devcontainer-cli \
         workspace isolation kafka compose-build registry resources multidb rabbitmq \
         webdev playwright egress)
# Real-gateway E2Es (spin up the actual huddle gateway; must run serially).
E2E=(e2e-aspire-sqlserver e2e-nested-egress e2e-toolchain-ca e2e-restart)

declare -A BUDGET=(
  [compose]=300 [testcontainers]=420 [buildx]=300 [privileged]=300 [k3d]=600
  [localstack]=420 [act]=420 [devcontainer-cli]=600 [workspace]=200 [isolation]=300
  [kafka]=700 [compose-build]=300 [registry]=400 [resources]=250 [multidb]=600
  [rabbitmq]=420 [webdev]=420 [playwright]=700 [egress]=500
  [e2e-aspire-sqlserver]=1500 [e2e-nested-egress]=700 [e2e-toolchain-ca]=1200 [e2e-restart]=900
)

SEL=("$@")
run_harness=(); run_e2e=()
if [ ${#SEL[@]} -eq 0 ]; then run_harness=("${HARNESS[@]}"); run_e2e=("${E2E[@]}");
else for s in "${SEL[@]}"; do case "$s" in e2e-*) run_e2e+=("$s");; *) run_harness+=("$s");; esac; done; fi
[ -n "${BATTERY_SKIP_E2E:-}" ] && run_e2e=()

OUT="$(mktemp -d)"; declare -A STATUS
build_testdc
if [ ${#run_e2e[@]} -gt 0 ]; then
  docker image inspect huddle-local:dind >/dev/null 2>&1 || { log "building gateway image"; docker build -t huddle-local:dind "$REPO/gateway" >"$OUT/gwbuild.log" 2>&1 || { echo "gateway build failed"; tail -5 "$OUT/gwbuild.log"; exit 1; }; }
  docker image inspect huddle-e2e-base:latest >/dev/null 2>&1 || { log "building e2e base image"; docker build -t huddle-e2e-base:latest -f "$HERE/Dockerfile.e2e-base" "$HERE" >"$OUT/basebuild.log" 2>&1 || { echo "base build failed"; tail -5 "$OUT/basebuild.log"; exit 1; }; }
fi

runone() { # <label> <cmd...>
  local label="$1"; shift; local budget="${BUDGET[$label]:-600}"
  log "=== $label (budget ${budget}s) ==="
  timeout "$budget" "$@" >"$OUT/$label.out" 2>"$OUT/$label.err"; STATUS[$label]=$?
  cat "$OUT/$label.out"; [ "${STATUS[$label]}" -ne 0 ] && tail -3 "$OUT/$label.err" 2>/dev/null | sed 's/^/  stderr: /'
}

for t in "${run_harness[@]}"; do [ -f "$HERE/tools/$t.sh" ] && runone "$t" bash "$HERE/tools/$t.sh" bridge || log "skip $t (missing)"; done
for e in "${run_e2e[@]}"; do [ -f "$HERE/$e.sh" ] && runone "$e" bash "$HERE/$e.sh" || log "skip $e (missing)"; done

ALLRUN=("${run_harness[@]}" "${run_e2e[@]}")
RESULTS="$REPO/docs/dind/RESULTS.md"
{
  echo "# DinD tool-compatibility results"
  echo
  echo "Generated by \`gateway/test/dind-compat/battery.sh\` — Design N (per-devcontainer"
  echo "private Docker daemon sharing the devcontainer netns). Each entry drives a real"
  echo "dev workflow end-to-end with functional assertions."
  echo
  echo "| Test | Result | Checks (PASS/FAIL) |"
  echo "|------|--------|--------------------|"
  for t in "${ALLRUN[@]}"; do
    [ -f "$OUT/$t.out" ] || continue
    p=$(grep -c '^PASS ' "$OUT/$t.out" 2>/dev/null || echo 0); f=$(grep -c '^FAIL ' "$OUT/$t.out" 2>/dev/null || echo 0)
    v="✅ pass"; [ "${STATUS[$t]}" -ne 0 ] && v="❌ fail"; [ "${STATUS[$t]}" -eq 124 ] && v="⏱ timeout"
    echo "| $t | $v | ${p}/${f} |"
  done
  echo
  for t in "${ALLRUN[@]}"; do
    [ -f "$OUT/$t.out" ] || continue
    echo "### $t"; echo '```'; grep -E '^(PASS|FAIL|NOTE) ' "$OUT/$t.out" 2>/dev/null || echo "(no assertions)"; echo '```'; echo
  done
} > "$RESULTS"
log "report -> $RESULTS"

fails=0; for t in "${ALLRUN[@]}"; do [ "${STATUS[$t]:-1}" -ne 0 ] && { fails=$((fails+1)); echo "FAILED: $t"; }; done
log "battery done — $(( ${#ALLRUN[@]}-fails ))/${#ALLRUN[@]} green"
exit $([ $fails -eq 0 ] && echo 0 || echo 1)
