#!/usr/bin/env bash
# DinD tool-compatibility runner. Runs each tool script against the real Design-N
# topology and writes a results report. Usage:
#   bash run.sh              # all tools
#   bash run.sh compose act  # a subset
#   NET=bridge bash run.sh   # override the network passed to Tier-1 tools
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$HERE/lib.sh"
build_testdc

ALL=(compose testcontainers buildx privileged k3d localstack act devcontainer-cli workspace isolation kafka compose-build registry resources helm kind concurrent nested2 exec-stream egress aspire)
TOOLS=("$@"); [ ${#TOOLS[@]} -eq 0 ] && TOOLS=("${ALL[@]}")
NET="${NET:-bridge}"

# Per-tool wall-clock budget (seconds).
declare -A BUDGET=(
  [compose]=300 [testcontainers]=420 [buildx]=300 [privileged]=300
  [k3d]=600 [localstack]=420 [act]=420 [devcontainer-cli]=600
  [workspace]=200 [isolation]=300 [kafka]=700 [compose-build]=300 [registry]=400 [resources]=250 [helm]=600 [kind]=700 [concurrent]=500 [nested2]=500 [exec-stream]=300 [egress]=500 [aspire]=1200
)

RESULTS="$HERE/../../../docs/dind/RESULTS.md"
OUTDIR="$(mktemp -d)"
declare -A STATUS

log "running: ${TOOLS[*]}"
for t in "${TOOLS[@]}"; do
  script="$HERE/tools/$t.sh"
  [ -f "$script" ] || { log "skip $t (no script)"; continue; }
  budget="${BUDGET[$t]:-600}"
  log "=== $t (budget ${budget}s) ==="
  # egress sets up its own network; other tools take NET as arg1.
  if [ "$t" = "egress" ]; then
    timeout "$budget" bash "$script" >"$OUTDIR/$t.out" 2>"$OUTDIR/$t.err"
  else
    timeout "$budget" bash "$script" "$NET" >"$OUTDIR/$t.out" 2>"$OUTDIR/$t.err"
  fi
  rc=$?
  STATUS[$t]=$rc
  cat "$OUTDIR/$t.out"
  [ $rc -ne 0 ] && { echo "  (exit $rc)"; tail -3 "$OUTDIR/$t.err" 2>/dev/null | sed 's/^/  stderr: /'; }
done

# ── Report ───────────────────────────────────────────────────────────────────
{
  echo "# DinD tool-compatibility results"
  echo
  echo "Generated by \`gateway/test/dind-compat/run.sh\` against Design N"
  echo "(per-devcontainer private Docker daemon sharing the devcontainer netns)."
  echo "Each tool is driven end-to-end with functional assertions, not just \"it ran\"."
  echo
  echo "| Tool | Result | Checks |"
  echo "|------|--------|--------|"
  for t in "${TOOLS[@]}"; do
    [ -f "$OUTDIR/$t.out" ] || continue
    p=$(grep -c '^PASS ' "$OUTDIR/$t.out" 2>/dev/null || echo 0)
    f=$(grep -c '^FAIL ' "$OUTDIR/$t.out" 2>/dev/null || echo 0)
    verdict="✅ pass"; [ "${STATUS[$t]}" -ne 0 ] && verdict="❌ fail"
    [ "${STATUS[$t]}" -eq 124 ] && verdict="⏱ timeout"
    echo "| $t | $verdict | ${p} pass / ${f} fail |"
  done
  echo
  for t in "${TOOLS[@]}"; do
    [ -f "$OUTDIR/$t.out" ] || continue
    echo "### $t"
    echo '```'
    grep -E '^(PASS|FAIL) ' "$OUTDIR/$t.out" 2>/dev/null || echo "(no assertions recorded)"
    echo '```'
    echo
  done
} > "$RESULTS"
log "report written: $RESULTS"

fails=0
for t in "${TOOLS[@]}"; do [ "${STATUS[$t]:-1}" -ne 0 ] && fails=$((fails+1)); done
log "done — $((${#TOOLS[@]}-fails))/${#TOOLS[@]} tools green"
exit $([ $fails -eq 0 ] && echo 0 || echo 1)
